// src/pages/FormPage.js
import React, { useState } from "react";
import { Send, CheckCircle, Sparkles, Loader } from "lucide-react";
import { saveSubmission } from "../utils/storage";
import { askAI } from "../utils/geminiApi";

const SYSTEM_PROMPT = `You are Medicare AI, a compassionate healthcare NGO assistant.
When given a patient, volunteer, or general contact form submission, write a warm personalised acknowledgement in 2-3 short sentences.

Follow these instructions exactly:
- If it is a volunteer submission, thank them for volunteering and keep the reply focused on appreciation for their volunteer support.
- If it is a patient support submission, mention the urgency level, say that we will be helping them, and thank them for registering.
- If it is a general contact submission, thank them for reaching out and also ask whether they know anyone who would like to volunteer, because we would be happy if they told them to volunteer.

Mention the person's name when natural. Be concise, caring, and clear.`;

const INITIAL = {
  role: "patient",
  name: "", email: "", phone: "",
  age: "", gender: "",
  department: "", urgency: "medium",
  skills: "", availability: "",
  subject: "", message: "",
};

function normalizeFormForRole(form, nextRole) {
  const base = { ...form, role: nextRole };

  if (nextRole === "patient") {
    return {
      ...base,
      urgency: base.urgency || "medium",
      skills: "",
      availability: "",
      subject: "",
    };
  }

  if (nextRole === "volunteer") {
    return {
      ...base,
      age: "",
      gender: "",
      department: "",
      urgency: "",
      subject: "",
    };
  }

  return {
    ...base,
    age: "",
    gender: "",
    department: "",
    urgency: "",
    skills: "",
    availability: "",
  };
}

export default function FormPage({ onSubmitted }) {
  const [form, setForm]       = useState(INITIAL);
  const [submitted, setSubmitted] = useState(false);
  const [aiResponse, setAiResponse] = useState("");
  const [loading, setLoading] = useState(false);
  const [referenceId, setReferenceId] = useState("");

  const set = (field, val) => setForm(f => ({ ...f, [field]: val }));

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    // 1. Save to localStorage
    const savedSubmission = saveSubmission(form);
    setReferenceId(`MC-${String(savedSubmission.id).slice(-6)}`);

    // 2. Build a summary for Medicare AI to respond to
    const summary = form.role === "patient"
      ? `Patient "${form.name}" (${form.age}y, ${form.gender}) submitted a support request for ${form.department} department. Urgency: ${form.urgency}. Message: "${form.message}"`
      : form.role === "volunteer"
      ? `Volunteer "${form.name}" registered. Skills: ${form.skills}. Availability: ${form.availability}. Message: "${form.message}"`
      : `Contact form from "${form.name}". Subject: "${form.subject}". Message: "${form.message}"`;

    // 3. Get AI auto-response
    try {
      const reply = await askAI(
        [{ role: "user", content: `Generate an acknowledgement for this submission: ${summary}` }],
        SYSTEM_PROMPT
      );
      setAiResponse(reply);
    } catch {
      setAiResponse("Thank you for your submission! Our team will review it and get back to you within 24 hours.");
    }

    setLoading(false);
    setSubmitted(true);
    if (onSubmitted) onSubmitted();
  };

  const reset = () => {
    setForm(INITIAL);
    setSubmitted(false);
    setAiResponse("");
    setReferenceId("");
  };

  if (submitted) {
    return (
      <div>
        <div className="page-header">
          <h2>Submission Received ✦</h2>
          <p>Your details have been recorded successfully.</p>
        </div>

        <div className="success-banner">
          <CheckCircle size={22} className="icon" />
          <div>
            <strong>Successfully submitted!</strong>
            <p>Reference ID: <strong>{referenceId}</strong></p>
          </div>
        </div>

        {loading ? (
          <div className="card" style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <Loader size={18} style={{ animation: "spin 1s linear infinite", color: "var(--teal)" }} />
            <span style={{ color: "var(--ink-soft)" }}>AI is generating your personalised response…</span>
          </div>
        ) : aiResponse && (
          <div className="card">
            <div className="summary-label"><Sparkles size={14} /> AI Auto-Response</div>
            <p className="summary-text">{aiResponse}</p>
            <p style={{ fontSize: 12, color: "var(--ink-soft)", marginTop: 10 }}>
              ✦ This response was generated by Medicare AI and sent automatically upon submission.
            </p>
          </div>
        )}

        <button className="btn btn-primary" onClick={reset}>
          Submit Another Form
        </button>
      </div>
    );
  }

  return (
    <div>
      <div className="page-header">
        <h2>Patient Support & Registration</h2>
        <p>Fill in the form below — our team reviews every submission within 24 hours.</p>
      </div>

      <div className="card">
        <div className="role-toggle">
          {[
            { val: "patient",   label: "🏥 Patient Support" },
            { val: "volunteer", label: "🤝 Volunteer Sign-Up" },
            { val: "contact",   label: "✉️ General Contact" },
          ].map(({ val, label }) => (
            <button
              key={val}
              type="button"
              className={`role-btn ${form.role === val ? "active" : ""}`}
              onClick={() => setForm(f => normalizeFormForRole(f, val))}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      <form onSubmit={handleSubmit}>
        {/* ── Common Fields ── */}
        <div className="card">
          <div className="card-title">Personal Information</div>
          <div className="card-sub">Basic contact details required for all submissions.</div>
          <div className="form-grid">
            <div className="form-group">
              <label>Full Name *</label>
              <input required value={form.name} onChange={e => set("name", e.target.value)} placeholder="e.g. Priya Sharma" />
            </div>
            <div className="form-group">
              <label>Email Address *</label>
              <input required type="email" value={form.email} onChange={e => set("email", e.target.value)} placeholder="priya@example.com" />
            </div>
            <div className="form-group">
              <label>Phone Number</label>
              <input type="tel" value={form.phone} onChange={e => set("phone", e.target.value)} placeholder="+91 98765 43210" />
            </div>

            {/* Patient-specific */}
            {form.role === "patient" && <>
              <div className="form-group">
                <label>Age</label>
                <input type="number" min="1" max="120" value={form.age} onChange={e => set("age", e.target.value)} placeholder="e.g. 34" />
              </div>
              <div className="form-group">
                <label>Gender</label>
                <select value={form.gender} onChange={e => set("gender", e.target.value)}>
                  <option value="">Select…</option>
                  <option>Male</option><option>Female</option><option>Non-binary</option><option>Prefer not to say</option>
                </select>
              </div>
              <div className="form-group">
                <label>Department Needed</label>
                <select value={form.department} onChange={e => set("department", e.target.value)}>
                  <option value="">Select department…</option>
                  <option>General Medicine</option><option>Cardiology</option><option>Paediatrics</option>
                  <option>Mental Health</option><option>Orthopaedics</option><option>Gynaecology</option>
                  <option>Dental</option><option>Eye Care</option>
                </select>
              </div>
              <div className="form-group">
                <label>Urgency Level</label>
                <select value={form.urgency} onChange={e => set("urgency", e.target.value)}>
                  <option value="low">🟢 Low — Routine check-up</option>
                  <option value="medium">🟡 Medium — Needs attention soon</option>
                  <option value="high">🔴 High — Urgent care needed</option>
                </select>
              </div>
            </>}

            {/* Volunteer-specific */}
            {form.role === "volunteer" && <>
              <div className="form-group">
                <label>Skills / Expertise</label>
                <input value={form.skills} onChange={e => set("skills", e.target.value)} placeholder="e.g. Nursing, Data Entry, Driving" />
              </div>
              <div className="form-group">
                <label>Availability</label>
                <select value={form.availability} onChange={e => set("availability", e.target.value)}>
                  <option value="">Select…</option>
                  <option>Weekdays</option><option>Weekends</option><option>Both</option><option>Flexible</option>
                </select>
              </div>
            </>}

            {/* Contact subject */}
            {form.role === "contact" && (
              <div className="form-group full">
                <label>Subject *</label>
                <input required value={form.subject} onChange={e => set("subject", e.target.value)} placeholder="e.g. Partnership inquiry" />
              </div>
            )}

            <div className="form-group full">
              <label>
                {form.role === "patient" ? "Describe your health concern" :
                 form.role === "volunteer" ? "Tell us about yourself" : "Your Message"} *
              </label>
              <textarea
                required
                value={form.message}
                onChange={e => set("message", e.target.value)}
                placeholder={
                  form.role === "patient" ? "Please describe your symptoms or what help you need…" :
                  form.role === "volunteer" ? "Why do you want to volunteer? Any relevant experience?" :
                  "Type your message here…"
                }
              />
            </div>
          </div>
        </div>

        <button type="submit" className="btn btn-primary" disabled={loading}>
          {loading
            ? <><Loader size={16} style={{ animation: "spin 1s linear infinite" }} /> Processing…</>
            : <><Send size={16} /> Submit Form</>
          }
        </button>
      </form>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
